name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint_type_unit:
    name: Lint, Typecheck & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install deps
        run: pnpm install --no-workspaces

      - name: Run ESLint
        run: pnpm lint

      - name: TypeScript Check
        run: pnpm tsc --noEmit

      - name: Run Unit Tests
        run: pnpm test:unit

  e2e_tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: lint_type_unit
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install deps
        run: pnpm install --no-workspaces

      - name: Run DB migrations
        run: pnpm prisma migrate deploy || echo "No Prisma"

      - name: Run E2E Tests
        run: pnpm test:e2e
